version: '2'
services:
#  apache:
#    build: apache
#    links:
#     - grafana
#     - subscribewarenbewegungenmongo
#     - publishwarenbewegungen
#    ports:
#     - "80:80"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    links:
     - zookeeper
#    ports:
#      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  nginx:
    build: ../bestand-kafka/bestandstream
    links:
#     - grafana
     - subscribewarenbewegungenmongo
     - publishwarenbewegungen
    ports:
     - "80:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
#  grafana:
#    # default admin user is admin/admin
#    image: grafana/grafana
#    environment:
#      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
#    ports:
#      - "3000:3000"
  publishwarenbewegungen:
    build: ../bestand-kafka/publishwarenbewegungen
    ports:
      - "8080:8080"
      - "8000:8000"
    links:
     - kafka
     - mongo
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  subscribewarenbewegungenmongo:
    build: ../bestand-kafka/subscribewarenbewegungenmongo
    ports:
      - "8081:8081"
      - "8001:8001"
    links:
     - kafka
     - mongo
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  subscribewarenbewegungenstreamprocessor:
    build: ../bestand-kafka/subscribewarenbewegungenstreamprocessor
    ports:
      - "8082:8082"
      - "8002:8002"
    links:
     - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  subscribebestandsbewegungen:
    build: ../bestand-kafka/subscribebestandsbewegungen
    ports:
      - "8083:8083"
      - "8003:8003"
    links:
     - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092